version: "3.9"
   
services:
  db:
    image: postgres
    ports:
        - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=travelApp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
  django:
    build: 
        context: ./backEnd
        dockerfile: Dockerfile
    entrypoint: "/entrypoint.sh"
    volumes:
      - ./backEnd:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  front:
    image: angulardjango
    build:
        context: ./frontEnd
        dockerfile: Dockerfile
    ports:
        - 4200:80
    depends_on:
        - django
    # volumes:
    #     - "./frontEnd:/app"
