version: "3.9"
   
services:
  db:
    image: postgres
    ports:
        - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=travelApp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
  django:
    build: 
        context: ./backEnd
        dockerfile: Dockerfile
    entrypoint: "/entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  front:
    build:
        context: ./frontEnd
        dockerfile: Dockerfile
    # command: /bin/sh -c "entrypoint.sh"
    entrypoint: "/entrypoint.sh"
    ports:
        - 4200:4200
    depends_on:
        - django
        - db
    volumes:
        - "./data/db:/var/lib/postgresql/data:rw"
        # - "/Users/zoran.pecic/Desktop/TravelingCompanionApp/frontEnd/entrypoint.sh:/app/entrypoint.sh"
