# Generated by Django 3.2.4 on 2021-06-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_transit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='transit_type',
        ),
        migrations.AddField(
            model_name='transit',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('booking', models.CharField(max_length=50, null=True)),
                ('booking_price', models.IntegerField()),
                ('start_destination', models.BooleanField(default=False)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='travelApp.trip')),
            ],
        ),
        migrations.AddField(
            model_name='transit',
            name='end_destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='travelApp.destination'),
        ),
        migrations.AddField(
            model_name='transit',
            name='start_destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='travelApp.destination'),
        ),
    ]
