# Generated by Django 3.2.4 on 2021-06-13 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelApp', '0005_auto_20210613_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='travelers', to=settings.AUTH_USER_MODEL),
        ),
    ]
