# Generated by Django 3.2.4 on 2021-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_alter_trip_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='transit_type',
            field=models.CharField(choices=[('train', 'TRAIN'), ('bus', 'BUS'), ('plane', 'PLANE'), ('ship', 'SHIP')], default='train', max_length=10),
        ),
    ]
